apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: sequential-pipeline
  annotations:
    tekton.dev/output_artifacts: '{"gcs-download": [{"key": "artifacts/$PIPELINERUN/gcs-download/data.tgz",
      "name": "gcs-download-data", "path": "/tmp/results.txt"}]}'
    tekton.dev/input_artifacts: '{"echo": [{"name": "gcs-download-data", "parent_task":
      "gcs-download"}]}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{"echo": [], "gcs-download": [["data", "$(results.data.path)"]]}'
    sidecar.istio.io/inject: "false"
    tekton.dev/template: ''
    pipelines.kubeflow.org/big_data_passing_format: $(workspaces.$TASK_NAME.path)/artifacts/$ORIG_PR_NAME/$TASKRUN_NAME/$TASK_PARAM_NAME
    pipelines.kubeflow.org/pipeline_spec: '{"description": "A pipeline with two sequential
      steps.", "inputs": [{"default": "gs://ml-pipeline/sample-data/shakespeare/shakespeare1.txt",
      "name": "url", "optional": true}], "name": "sequential-pipeline"}'
  labels:
    pipelines.kubeflow.org/pipelinename: ''
    pipelines.kubeflow.org/generation: ''
spec:
  params:
  - name: url
    value: gs://ml-pipeline/sample-data/shakespeare/shakespeare1.txt
  pipelineSpec:
    params:
    - name: url
      default: gs://ml-pipeline/sample-data/shakespeare/shakespeare1.txt
    tasks:
    - name: gcs-download
      params:
      - name: url
        value: $(params.url)
      taskSpec:
        steps:
        - name: main
          args:
          - gsutil cat $0 | tee $1
          - $(inputs.params.url)
          - $(results.data.path)
          command:
          - sh
          - -c
          image: google/cloud-sdk:279.0.0
        params:
        - name: url
        results:
        - name: data
          type: string
          description: /tmp/results.txt
        metadata:
          labels:
            pipelines.kubeflow.org/cache_enabled: "true"
          annotations: {}
    - name: echo
      params:
      - name: gcs-download-data
        value: $(tasks.gcs-download.results.data)
      taskSpec:
        steps:
        - name: main
          args:
          - echo "$0"
          - $(inputs.params.gcs-download-data)
          command:
          - sh
          - -c
          image: library/bash:4.4.23
        params:
        - name: gcs-download-data
        metadata:
          labels:
            pipelines.kubeflow.org/cache_enabled: "true"
          annotations: {}
